name: Annihilation
version: 1.0
api: 2.0.0
main: Annihilation\Annihilation
author: Minetox team & Majovec
description: Annihilation minigame

commands:
    class:
        description: "Select game kit"
    blue:
        description: "join to blue team"
    red:
        description: "join to red team"
    yellow:
        description: "join to yellow team"
    green:
        description: "join to green team"
    lobby:
        description: "send to main lobby"
    stats:
        description: "show your game stats"
    msg:
        description: "send private message to another player"
    vote:
        description: "vote command"
    start:
        description: "start command"
